"""in reply to post field has default value 0 

Revision ID: 5438c03450bf
Revises: 41263fe9fe92
Create Date: 2023-07-20 20:23:25.145667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5438c03450bf'
down_revision = '41263fe9fe92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
