"""Post:text field updated

Revision ID: 54426a65108a
Revises: f249bc413cd6
Create Date: 2023-07-17 20:30:39.527189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54426a65108a'
down_revision = 'f249bc413cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.String(), nullable=True))
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###
