"""Users, Posts, Reactions and Badges added

Revision ID: 67de35ff560f
Revises: 9636c29d3e29
Create Date: 2023-07-12 21:43:12.979939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67de35ff560f'
down_revision = '9636c29d3e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
