"""Users, Posts, Reactions and Badges added

Revision ID: 9636c29d3e29
Revises: 8bac19378ef9
Create Date: 2023-07-12 21:05:20.642161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9636c29d3e29'
down_revision = '8bac19378ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
