"""Users, Posts, Reactions and Badges added

Revision ID: 97818f4cdbdd
Revises: 67de35ff560f
Create Date: 2023-07-12 21:51:19.611451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97818f4cdbdd'
down_revision = '67de35ff560f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
