"""Relationship between User and Badge added

Revision ID: ca0f2b1e406a
Revises: 55326f0953c1
Create Date: 2023-07-10 23:58:09.121775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0f2b1e406a'
down_revision = '55326f0953c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
