"""Users, Posts, Reactions and Badges added

Revision ID: f249bc413cd6
Revises: 97818f4cdbdd
Create Date: 2023-07-12 21:58:40.154609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f249bc413cd6'
down_revision = '97818f4cdbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
